development:
  url: postgresql://localhost/gallerey_demo_app_development

test:
  url: postgresql://localhost/gallerey_demo_app_test

production:
  url: <%= ENV["DATABASE_URL"] %>
  password:  <%= ENV["DATABASE_PASSWD"] %>
  pool: 16
